groups:
- name: example
  rules:
  - record: code:prometheus_http_requests_total:sum
    expr: sum by (code) (prometheus_http_requests_total)

- name: remote prometheus
  rules:
  - alert: NodeStatus
    expr: up{instance="34.86.5.170:9090",  job="prometheus-test"} == 1
    for: 10s
    labels:
      severity: critical
    annotations:
      summary: "{{ $labels.instance }} is down"